//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretNumber.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecretNumber.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не смог разобрать чего вы от меня хотите..
        /// </summary>
        internal static string Default_GameLauncher {
            get {
                return ResourceManager.GetString("Default_GameLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не понял! {0} попыток осталось...
        /// </summary>
        internal static string Default_GameMaster {
            get {
                return ResourceManager.GetString("Default_GameMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Угадайте секретное число. Чтобы вызвать возможные команды введите help.
        /// </summary>
        internal static string DefaultTextHelpCommand {
            get {
                return ResourceManager.GetString("DefaultTextHelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра закончена.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры игры: диапазон загадывания от {0} до {1}, количество попыток: {2}.
        /// </summary>
        internal static string GameParameters {
            get {
                return ResourceManager.GetString("GameParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра загадала новое секретное число. Количество попыток восстановлено..
        /// </summary>
        internal static string GameRestart {
            get {
                return ResourceManager.GetString("GameRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра загадала секретное число. Попробуйте его угадать!.
        /// </summary>
        internal static string GameStarted {
            get {
                return ResourceManager.GetString("GameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенное число больше отгадываемого. {0} попыток осталось...
        /// </summary>
        internal static string GuessedBiggerThanSecret {
            get {
                return ResourceManager.GetString("GuessedBiggerThanSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы угадали секретное число! Попробуйте отгадать новое число..
        /// </summary>
        internal static string GuessedRight {
            get {
                return ResourceManager.GetString("GuessedRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенное число меньше отгадываемого. {0} попыток осталось...
        /// </summary>
        internal static string GuessedSmallerThanSecret {
            get {
                return ResourceManager.GetString("GuessedSmallerThanSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \nВот список доступных команд для игры \&quot;Секретное число\&quot; \nnew - загадать новое число и восстановить число попыток \nquit - закончить игру \nhelp - вызвать список доступных команд.
        /// </summary>
        internal static string HelpCommand {
            get {
                return ResourceManager.GetString("HelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уже израсходовали все попытки. Попробуйте отгадать новое число..
        /// </summary>
        internal static string NoTriesLeftWarning {
            get {
                return ResourceManager.GetString("NoTriesLeftWarning", resourceCulture);
            }
        }
    }
}
